### ISSUE TITLE
[Feature request] GPG support?

### ISSUE THREAD

**Issue by vatterspun** [Sigmanor/Crypto-Notepad#1]
I don't know if this is high priority or out of scope but I generally save my encrypted notepad material using GPG so I can save and open encrypted text on multiple devices, since that format has fairly broad support.

**Comment by Sigmanor** [comment]
Yes, nice idea, I'll see what i can do.

**Comment by vatterspun** [comment]
:) Great, thanks

**Comment by vatterspun** [comment]
One additional note, if adding GPG functionality is too complex, it might be simpler to implement a 7zip file save scheme.  That program has open command-line tools that could run for both compression and encryption.  The files created would also be widely accessible (and it's more popular than GPG).

**Comment by Sigmanor** [comment]
@vatterspun 
Can you give me some files for tests? Encrypted with GPG with password to decrypt.

Also how you see GPG/7zip file save scheme implementation in this app? App already have own format with AES encryption, you want add new format?

**Comment by vatterspun** [comment]
> Also how you see GPG/7zip file save scheme implementation in this app? 

GPG: it has an existing schema, generating text files like the one below with the file extension .GPG

> App already have own format with AES encryption, you want add new format?

If you go with 7zip, I would suggest replacing your current format.  The reason only reason to go with this as a file save mechanism is for compatibility and compression.  It doesn't have superior security.

----

> Can you give me some files for tests? Encrypted with GPG with password to decrypt.

I can but it's actually a public key-based system; like web traffic encryption, there's a key exchange that creates a secure connection.

So for example, here's my public key and a quick message:

Pubkey:
http://pastebin.com/eKmHiAYt

Message:
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMA2jpXg6nVwSiAQ//Q0AfowGbUfdsGPX4Z/CGuyESuR+Ex1lgjYgPyhERfvYq
z3LII8ewioK/gqjWOXz+hegxun4S+lahOqIE7wQ0xd2G9lrDBAe0SdKWFl4RcmjD
iAMd4eAuOmhyWHm2WxNEWpwfNiLHuT2pIirVIy6gvBLjxRggwFTr6zUjoxchWvW7
jJFvZn9gCcYi3hveXpg3tfUohjdmePPHHcI2RqVnNh6pRB+s4uHDJznklSIPAjyO
0LgKhyhvDSLrKVPLiYi4hueY8C0BQ48BwdNpiRr5xwN1A/1iS9cAFnn2m7EOHpTw
0l7NOrH1PBFxh7rK/4bHe3vD39iLKGmvDxXbp5LT3nzEuG2SkCPF6HIblB2cHX8t
mHaxq8PJiSMTjtiQuD4z8seUP2QEL5Tjk7FYtYEKqWH8uoFgKbr9lZ8S6j067bZp
EKr5NThqygASn0ibEyjlbsBx020313cXEBhBHGbpfvsMNSwIR6bXMQTt+eHJI68M
T21S/zbuRiR8Tix8D1PRyr0fq30XDGS7fEfor5yo7UWpfsDkL+VlNnZYzjvNQLe4
pB0AIR4Mt2Ugb/b+8gr6oMAgN2orUT3NCxfsR28ZOlcNlP4vlQsoYSc8WW+O2WzQ
C8kM+BRZBK10tX8Rq1hxXtDHQhYZ6JPlppWMnwMMcuxgvBGoj6dJ00WZdUlsbO/S
cAHDV8+aNyPrBMyvM77RHPT7kyI6JHQYI94SJtueVMLKx4svcjo9P4Mtc33A4e/h
frovHNyD+r2CPe+ZyEEpM/Np3HAJrk+DwaLg14kNVz/z434o0nDLMsqy+2m+A7uB
JbkZq0S2w1daiujs3oUhudI=
=VEc+
-----END PGP MESSAGE-----
```

**Comment by Sigmanor** [comment]
Finally, a clear project [ideology](https://github.com/Sigmanor/Crypto-Notepad/blob/master/CONTRIBUTING.md#things-that-will-never-be-in-this-project) was formed. And, unfortunately, the proposed improvements are not included in this ideology. So, this issue  is closed.
