### ISSUE TITLE
[Feature request]  Drag and Drop support for TXT and CNP files

### ISSUE THREAD

**Issue by Sigmanor** [Sigmanor/Crypto-Notepad#2]
It would be nice if Crypto Notepad supports drag and drop for TXT and CNP files. If a TXT file is dragged and dropped into Crypto Notepad it just opens it, while if a CNP file is dragged and dropped the program opens "Enter the encryption key:" dialog.

**Comment by smaragdus** [comment]
Thanks for adding this feature request to your "to do" list. ;)

**Comment by vatterspun** [comment]
@Sigmanor 

Was just about to suggest that.  Thanks.

**Comment by Sigmanor** [comment]
Please update to new version. If you find any bug, open a new issue.

**Comment by smaragdus** [comment]
**@Sigmanor**
Thank you for drag&drop support too. I could not respond earlier due to personal problems.
Someone at The Portable Freeware asked something I was about to ask myself- have you considered implementation of tabs?

**Comment by Sigmanor** [comment]
@smaragdus about tabs, no (because I do not need this function) but I can add, it is easy to implement.

**Comment by smaragdus** [comment]
**@Sigmanor**
I think that tabs would be very useful when one is working with multiple text snippets at the same time. So for me tabs would be great! ;)
