### ISSUE TITLE
[Feature request] Detect URLs and mailto: links

### ISSUE THREAD

**Issue by Sigmanor** [Sigmanor/Crypto-Notepad#3]
It would be very handy if Crypto Notepad could detect URLs and mailto: links so these could be opened (either via double click or via CTRL+click) in the default web browser and in the default mail client.

**Comment by smaragdus** [comment]
I do think that URL detection will be very handy, thanks!

**Comment by Sigmanor** [comment]
Please update to new version. You can open links when holding SHIFT key.

**Comment by smaragdus** [comment]
**@Sigmanor**
Thank you very much! Detection of URL and mailto: links work fine! Someone else updated the database entry at The Portable Freeware.
