### ISSUE TITLE
[Feature request] Add more cryptographic algorithms

### ISSUE THREAD

**Issue by Sigmanor** [Sigmanor/Crypto-Notepad#5]
Add support for Blowfish or/and SHA-3

**Comment by vatterspun** [comment]
Why Blowfish?  I don't think it's any faster or more secure than other methods.  In fact there are two successors to that algorithm by the same authors.

**Comment by Sigmanor** [comment]
@vatterspun One of the users wrote me and asking for the adding support for Blowfish or/and SHA-3

**Comment by vatterspun** [comment]
Well I guess I'd decline that request if I were in your shoes, but certainly it's your call.

**Comment by Sigmanor** [comment]
@vatterspun But this is not a replacement for the current algorithms, it's adding one more, I do not think it's very critical. In any case, unfortunately I now do not have time to add anything to the app. So far, everything will be as it is.

**Comment by vatterspun** [comment]
> unfortunately I now do not have time to add anything to the app. So far, everything will be as it is.

Understood, thanks for responding.

**Comment by Sigmanor** [comment]
Finally, a clear project [ideology](https://github.com/Sigmanor/Crypto-Notepad/blob/master/CONTRIBUTING.md#things-that-will-never-be-in-this-project) was formed. And, unfortunately, the proposed improvements are not included in this ideology. So, this issue  is closed.
