### ISSUE TITLE
Quite a few cryptographic insecurities

### ISSUE THREAD

**Issue by tuxxy** [Sigmanor/Crypto-Notepad#7]
I just searched "AES encryption" on Github to see what poor implementations of AES I could find and I came across your implementation.

There's quite a few issues with how you're using it here.

1. Insecure initialization vector -- I'll leave this to you to figure out why not picking a secure random IV for every encryption you do is bad. "16CHARSLONG12345" is most definitely not a secure, random IV.
2. Insecure password hashing -- Use a stronger hashing function like Bcrypt, scrypt, or pbkdf2.
3. Unauthenticated cipher mode -- You're using CBC without any authentication of any kind. Look into using CBC with HMAC or a different AEAD like GCM mode or using libsodium's `SecretBox`.
4. Ideally, you would derive different keys for each file. It looks like you're using the same key for every file.

There's probably more, but this was a quick look over.

Checkout "_Cryptography Engineering_" by Bruce Schneier and Niels Ferguson to learn how to safely and properly implement cryptographic functions like this.

**Comment by Sigmanor** [comment]
Thanks for the helpful advice.

**Comment by vatterspun** [comment]
I so rarely see anything like this on crypto development and one of the reasons that security programs need to be open source.  Thanks.

**Comment by Sigmanor** [comment]
#9

**Comment by Sigmanor** [comment]
Small improvements in solving this issue - #9

**Comment by h5p9sl** [comment]
I don't know if you necessarily need to worry about the hashing algorithm since the program only uses the hashing algorithm for generating a key hash and using it with the Rijndael cipher.
I'm by no means an expert though, so I could be wrong.

**Comment by Sigmanor** [comment]
More improvements in solving this issue #10

**Comment by Sigmanor** [comment]
Solved in pull requests  #9 #10  by @h5p9sl
