### ISSUE TITLE
[BUG] Text cursor (caret) is changing position when I'm saving file

### ISSUE THREAD

**Issue by Avaray** [Sigmanor/Crypto-Notepad#8]
No matter if I choose "File > Save" or use combination "CTRL + S", text cursor will move to last line.

Im using v1.1.1 in Win10 (x64).

**Comment by Sigmanor** [comment]
It's not a bug, it's a feature :D 

But if seriously, it's done on purpose. I do not remember why it was necessary. If it hinders for you, I will fix it somehow.

**Comment by Avaray** [comment]
I see. It would be great to have option to Enable/Disafle this feature :)
